using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace main
{
    
    public class MainClass
    {
        
        static void Main(string[] args)
        {
            List<string> lines = new List<string>();
            List<string> output = new List<string>();
            
            //int pointer = 0;
            
            try
            {
                using (StreamReader sr = new StreamReader("src.txt"))
                {
                    string line;
                    
                    while ((line = sr.ReadLine()) != null)
                    {
                        lines.Add(line);
                    }
                }
                
                int lineCount = 1;
                
                foreach (string s in lines)
                {
                    string[] split = s.Split(' ');
                    //split[0] = s.Substring(1);
                    split[1] = s.Substring(s.IndexOf(' ') + 1);
                    
                    // Add message
                    
                    output.Add("Auto generated by Brainfuck Compiler \n");
                    
                    char[] array = split[1].ToCharArray();
                    int pointer = 0;
                    
                    switch (split[0])
                    {
                        case "print":
                            foreach (char c in array)
                            {
                                int ascii = (int) c;
                                
                                for (int i = 0; i < ascii; i++)
                                    output.Add("+");
                                
                                output.Add(".");
                                
                                for (int i = 0; i < ascii; i++)
                                    output.Add("-");
                            }
                        break;
                        
                        case "input":
                            try
                            {
                                int cell = int.Parse(split[1]);
                                
                                while (pointer > cell) {
                                    output.Add("<");
                                    pointer--;
                                }
                                
                                while (pointer < cell) {
                                    output.Add(">");
                                    pointer++;
                                }
                                
                                output.Add(",");
                            }
                            catch (Exception)
                            {
                                Console.WriteLine("Error Compiling: Invalid Number in command input at line " + lineCount);
                            }
                        break;
                    }
                    
                    lineCount++;
                }
                
                // Write
                
                using (StreamWriter sw = new StreamWriter("out.bf"))
                {
                    foreach (string str in output)
                    {
                        sw.Write(str);
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("Error: " + e.Message);
            }
            
            Console.ReadLine();
        }
    }
}
