using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace main
{
    
    public class MainClass
    {
        
        static void Main(string[] args)
        {
            List<string> lines = new List<string>();
            List<string> output = new List<string>();
            
            int[] cells = new int[999];
            
            for (int i = 0; i < cells.Length; i++)
                cells[i] = 0;
            
            int pc = 0;
            
            try
            {
                using (StreamReader sr = new StreamReader("src.txt"))
                {
                    string line;
                    
                    while ((line = sr.ReadLine()) != null)
                    {
                        lines.Add(line);
                    }
                }
                
                int lineCount = 1;
                
                foreach (string s in lines)
                {
                    string[] split = s.Split(' ');
                    split[1] = s.Substring(s.IndexOf(' ') + 1);
                    
                    // Add message
                    
                    //output.Add("Auto generated by Brainfuck Compiler \n");
                    
                    char[] array = split[1].ToCharArray();
                    
                    switch (split[0])
                    {
                        case "print":
                            bool isVariable = split[1].StartsWith("$");
                            
                            if (!isVariable)
                            {
                                foreach (char c in array)
                                {
                                    int ascii = (int) c;
                                    
                                    for (int i = 0; i < ascii; i++)
                                    {
                                        output.Add("+");
                                        cells[pc]++;
                                    }
                                    
                                    output.Add(".");
                                    
                                    for (int i = 0; i < ascii; i++)
                                    {
                                        output.Add("-");
                                       
                                        cells[pc]--;
                                    }
                                }
                            }
                            else // isVariable = true
                            {
                                try
                                {
                                    int cell = int.Parse(split[1].Substring(1));
                                    
                                    while (pc > cell)
                                    {
                                        output.Add("<");
                                        pc--;
                                    }
                                    
                                    while (pc < cell)
                                    {
                                        output.Add(">");
                                        pc++;
                                    }
                                    
                                    output.Add(".");
                                }
                                catch (Exception)
                                {
                                    
                                }
                            }
                        break;
                        
                        case "input":
                            try
                            {
                                int cell = int.Parse(split[1]);
                                
                                while (pc > cell)
                                {
                                    output.Add("<");
                                    pc--;
                                }
                                
                                while (pc < cell)
                                {
                                    output.Add(">");
                                    pc++;
                                }
                                
                                output.Add(",");
                            }
                            catch (Exception)
                            {
                                Console.WriteLine("Error Compiling: Invalid number in command 'input' at line " + lineCount);
                            }
                        break;
                        
                        case "moveptr":
                            switch (split[1])
                            {
                                case "left":
                                    output.Add("<");
                                    pc--;
                                break;
                                
                                case "right":
                                    output.Add(">");
                                    pc++;
                                break;
                            }
                        break;
                        case "set":
                            try
                            {
                                string[] spl = s.Split(' ');
                                
                                int cell = int.Parse(spl[1]);
                                int val = int.Parse(spl[2]);
                                
                                while (pc > cell)
                                {
                                    output.Add("<");
                                    pc--;
                                }
                                
                                while (pc < cell)
                                {
                                    output.Add(">");
                                    pc++;
                                }
                                
                                /////////////
                                
                                while (cells[pc] > val)
                                {
                                    output.Add("-");
                                    cells[pc]--;
                                }
                                
                                while (cells[pc] < val)
                                {
                                    output.Add("+");
                                    cells[pc]++;
                                }
                            }
                            catch (Exception)
                            {
                                Console.WriteLine("Exception");
                            }
                        break;
                    }
                    
                    lineCount++;
                }
                
                // Write
                
                using (StreamWriter sw = new StreamWriter("out.bf"))
                {
                    foreach (string str in output)
                    {
                        sw.Write(str);
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("Error while compiling: " + e.Message);
            }
            
            Console.ReadLine();
        }
    }
}
